const CartActionTypes = {
	ADD_ITEM_START: 'ADD_ITEM_START',
	ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
	ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE',
	CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
	REMOVE_ITEM: 'REMOVE_ITEM',
	CLEAR_CART: 'CLEAR_CART'
}

export default CartActionTypes;