const GalleryActionTypes = {
	FETCH_GALLERY_START: 'FETCH_GALLERY_START',
	FETCH_GALLERY_SUCCESS: 'FETCH_GALLERY_SUCCESS',
	FETCH_GALLERY_FAILURE: 'FETCH_GALLERY_START',
}

export default GalleryActionTypes;